import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SessionProvider, ThemeProvider } from "./providers";
import { SiteHeader } from "@/components/header";
import { Toaster } from "sonner";
import { validateRequest } from "@/lib/auth";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "300 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await validateRequest();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SessionProvider value={session}>
            <main className="">
              <script
                id="ze-snippet"
                src="https://static.zdassets.com/ekr/snippet.js?key=c10d619d-f9ff-47c0-84bf-260ae80b5013"
                async
              ></script>
              <SiteHeader />
              <main>
                {children}
              </main>
            </main>
          </SessionProvider>
        </ThemeProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
